// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("blazey.substituter")]
[assembly: AssemblyProductAttribute("blazey.substituter")]
[assembly: AssemblyDescriptionAttribute("A Castle Windsor facility that substitutes components for unit testing purposes.")]
[assembly: AssemblyVersionAttribute("0.1")]
[assembly: AssemblyFileVersionAttribute("0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1";
    }
}
