// <auto-generated/>

using System.Reflection;

[assembly: AssemblyTitle("blazey.substituter")]
[assembly: AssemblyProduct("blazey.substituter")]
[assembly: AssemblyDescription("A Castle Windsor facility that substitutes components for unit testing purposes.")]
[assembly: AssemblyVersion("1.0")]
[assembly: AssemblyFileVersion("1.0")]
namespace blazey.substituter.Properties {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
